// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrig2zMSoBMnbsF6mCa1oZNRWU6icrba4',
    appId: '1:780483403495:web:1938ba9dac0c013815cc42',
    messagingSenderId: '780483403495',
    projectId: 'loginsignup-1efcd',
    authDomain: 'loginsignup-1efcd.firebaseapp.com',
    storageBucket: 'loginsignup-1efcd.appspot.com',
    measurementId: 'G-LPDFZ7W9V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4mxK1WEc5CvC1rVK6mrJHlvcBiYpWz2E',
    appId: '1:780483403495:android:476a1d354f0dcefc15cc42',
    messagingSenderId: '780483403495',
    projectId: 'loginsignup-1efcd',
    storageBucket: 'loginsignup-1efcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJObPnPUbo-ha0u8uis-XHCkvQsJHMinE',
    appId: '1:780483403495:ios:e4f8a3fb8d6358cf15cc42',
    messagingSenderId: '780483403495',
    projectId: 'loginsignup-1efcd',
    storageBucket: 'loginsignup-1efcd.appspot.com',
    androidClientId: '780483403495-qpkia4nibn1becgkgsd7a589qnpdb0o0.apps.googleusercontent.com',
    iosClientId: '780483403495-u20dt77mq8mk0adifes7pc5ejqj7mqo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJObPnPUbo-ha0u8uis-XHCkvQsJHMinE',
    appId: '1:780483403495:ios:e4f8a3fb8d6358cf15cc42',
    messagingSenderId: '780483403495',
    projectId: 'loginsignup-1efcd',
    storageBucket: 'loginsignup-1efcd.appspot.com',
    androidClientId: '780483403495-qpkia4nibn1becgkgsd7a589qnpdb0o0.apps.googleusercontent.com',
    iosClientId: '780483403495-u20dt77mq8mk0adifes7pc5ejqj7mqo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );
}
